Initial implementation viber connector
wso2-extensions/esb-connector-viber pull request #1
Opened 2019-03-11 08:51 UTC by Sarangikaethugala

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2019-03-13 12:42 UTC, Kanapriya requested changes

2019-03-13 12:42 UTC, Kanapriya commented on src/main/assembly/filter.properties
> +product.version=6.1.1
Didn't you check with latest EI version? Why still have 6.1.1?

2019-03-13 12:42 UTC, Kanapriya commented on src/main/resources/broadcastMessage/broadcastCarouselContentMessage.xml
> +                }
Seems there is a formatting issue?

2019-03-13 12:42 UTC, Kanapriya commented on src/main/resources/broadcastMessage/broadcastContactMessage.xml
> +                }
Formatting issue, check this throughout the PR

2019-03-14 08:18 UTC, Kanapriya commented on src/test/resources/testng.xml
> +</suite>
Add new line here

2019-03-14 08:18 UTC, Kanapriya commented on src/test/resources/automation.xml
> +</automation>
Add new line here

2019-03-14 10:23 UTC, Biruntha commented on .editorconfig
> +
Do we need this hidden file? If not pls remove

2019-03-14 10:26 UTC, Biruntha commented on README.md
> +| [1.0.0](https://github.com/wso2-extensions/esb-connector-viber/releases/tag/org.wso2.carbon.connector.viber-1.0.0)  | V7.3.0| ESB 6.4.0 |
I think link should be
https://github.com/wso2-extensions/esb-connector-viber/releases/tag/org.wso2.carbon.esb.connector.viber-1.0.0
Check this and update

2019-03-14 10:30 UTC, Biruntha commented on docs/broadcastMessage.md
> +| [broadcastVideoMessage](#Broadcast-video-message) |Broadcast a video.|
You need to add Sample response and Related API doc for all the methods.
Fix in all the places

2019-03-14 10:32 UTC, Biruntha commented on docs/keyboardMessage.md
> +| [sendKeyboardVideo](#Send-keyboard-with-video-message) |Send a keyboard with video message.|
Add Sample response and Related API doc for all the methods

2019-03-14 10:33 UTC, Biruntha commented on docs/message.md
> +| [sendVideoMessage](#Send-video-message) |Send a video message.|
Add Sample response and Related API doc for all the methods

2019-03-14 10:34 UTC, Biruntha commented on src/main/resources/accountInfo/getAccountInfo.xml
> +                      uri-template="{uri.var.apiUrl}/pa/get_account_info"/>
Move this line to above

2019-03-14 10:35 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastContactMessage.xml
> +                      uri-template="{uri.var.apiUrl}/pa/broadcast_message"/>
Move this line to above

2019-03-14 10:36 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastFileMessage.xml
> +            payload.sender.avatar = senderAvatarUrl;
Fix Formatting issue

2019-03-14 10:36 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastFileMessage.xml
> +            if ( senderAvatarUrl!= null && senderAvatarUrl != "") {
```suggestion
            if ( senderAvatarUrl != null && senderAvatarUrl != "") {
```

2019-03-14 10:36 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastFileMessage.xml
> +            if( trackingData != null && trackingData != ""){
```suggestion
            if(trackingData != null && trackingData != "") {
```

2019-03-14 10:37 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastFileMessage.xml
> +            payload.tracking_data = trackingData;
Fix Formatting issue

2019-03-14 10:37 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastFileMessage.xml
> +            payload.min_api_version = minApiVersion;
Fix Formatting issue

2019-03-14 10:37 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastFileMessage.xml
> +            if( minApiVersion != null && minApiVersion != ""){
```suggestion
            if(minApiVersion != null && minApiVersion != "") {
```

2019-03-14 10:37 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastFileMessage.xml
> +                      uri-template="{uri.var.apiUrl}/pa/broadcast_message"/>
Move this line to above

2019-03-14 10:37 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastLocationMessage.xml
> +            payload.sender.avatar = senderAvatarUrl;
Fix Formatting issue

2019-03-14 10:38 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastLocationMessage.xml
> +            if ( senderAvatarUrl!= null && senderAvatarUrl != "") {
```suggestion
            if (senderAvatarUrl != null && senderAvatarUrl != "") {
```

2019-03-14 10:38 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastLocationMessage.xml
> +            if( trackingData != null && trackingData != ""){
```suggestion
            if(trackingData != null && trackingData != "") {
```

2019-03-14 10:56 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastLocationMessage.xml
> +            if( minApiVersion != null && minApiVersion != ""){
```suggestion
            if(minApiVersion != null && minApiVersion != "") {
```

2019-03-14 10:56 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastLocationMessage.xml
> +            payload.min_api_version = minApiVersion
Fix Formatting issue

2019-03-14 10:57 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastLocationMessage.xml
> +                      uri-template="{uri.var.apiUrl}/pa/broadcast_message"/>
Move this line to above

2019-03-14 10:57 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastPictureMessage.xml
> +            if ( senderAvatarUrl!= null && senderAvatarUrl != "") {
```suggestion
            if (senderAvatarUrl != null && senderAvatarUrl != "") {
```

2019-03-14 10:58 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastPictureMessage.xml
> +            payload.sender.avatar = senderAvatarUrl;
Fix Formatting issue

2019-03-14 10:58 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastPictureMessage.xml
> +            if( trackingData != null && trackingData != ""){
```suggestion
            if(trackingData != null && trackingData != "") {
```

2019-03-14 10:58 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastPictureMessage.xml
> +            payload.tracking_data = trackingData;
Fix Formatting issue

2019-03-14 10:58 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastPictureMessage.xml
> +            payload.thumbnail = thumbnailUrl;
Fix Formatting issue

2019-03-14 10:58 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastPictureMessage.xml
> +            payload.min_api_version = minApiVersion;
Fix Formatting issue

2019-03-14 10:59 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastPictureMessage.xml
> +            if( minApiVersion != null && minApiVersion != ""){
```suggestion
            if(minApiVersion != null && minApiVersion != "") {
```

2019-03-14 10:59 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastPictureMessage.xml
> +            if( thumbnailUrl != null && thumbnailUrl != ""){
```suggestion
            if(thumbnailUrl != null && thumbnailUrl != "") {
```

2019-03-14 10:59 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastPictureMessage.xml
> +                      uri-template="{uri.var.apiUrl}/pa/broadcast_message"/>
Move this line to above

2019-03-14 10:59 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastStickerMessage.xml
> +            payload.sender.avatar = senderAvatarUrl;
Fix Formatting issue

2019-03-14 11:00 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastStickerMessage.xml
> +            if ( senderAvatarUrl!= null && senderAvatarUrl != "") {
```suggestion
            if (senderAvatarUrl != null && senderAvatarUrl != "") {
```

2019-03-14 11:00 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastStickerMessage.xml
> +            if( trackingData != null && trackingData != ""){
```suggestion
            if(trackingData != null && trackingData != "") {
```

2019-03-14 11:00 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastStickerMessage.xml
> +            payload.tracking_data = trackingData;
Fix Formatting issue

2019-03-14 11:00 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastStickerMessage.xml
> +            if( minApiVersion != null && minApiVersion != ""){
```suggestion
            if(minApiVersion != null && minApiVersion != "") {
```

2019-03-14 11:04 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastStickerMessage.xml
> +            payload.min_api_version = minApiVersion;
Fix Formatting issue

2019-03-14 11:04 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastStickerMessage.xml
> +                      uri-template="{uri.var.apiUrl}/pa/broadcast_message"/>
Move this line to above.

2019-03-14 11:04 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastTextMessage.xml
> +            payload.sender.avatar = senderAvatarUrl;
Fix Formatting issue

2019-03-14 11:04 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastTextMessage.xml
> +            if ( senderAvatarUrl != null && senderAvatarUrl != "") {
```suggestion
            if (senderAvatarUrl != null && senderAvatarUrl != "") {
```

2019-03-14 11:05 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastTextMessage.xml
> +            payload.min_api_version = minApiVersion;
Fix Formatting issue

2019-03-14 11:05 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastTextMessage.xml
> +            payload.tracking_data = trackingData;
Fix Formatting issue

2019-03-14 11:05 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastTextMessage.xml
> +            if( trackingData != null && trackingData != ""){
```suggestion
            if(trackingData != null && trackingData != "") {
```

2019-03-14 11:05 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastTextMessage.xml
> +            if( minApiVersion != null && minApiVersion != ""){
```suggestion
            if(minApiVersion != null && minApiVersion != "") {
```

2019-03-14 11:05 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastTextMessage.xml
> +                      uri-template="{uri.var.apiUrl}/pa/broadcast_message"/>
Move this line to above.. Check in all the files and fix

2019-03-14 11:06 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastUrlMessage.xml
> +            payload.sender.avatar = senderAvatarUrl;
Fix Formatting issue

2019-03-14 11:06 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastUrlMessage.xml
> +            if ( senderAvatarUrl != null && senderAvatarUrl != "") {
```suggestion
            if (senderAvatarUrl != null && senderAvatarUrl != "") {
```

2019-03-14 11:06 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastUrlMessage.xml
> +            payload.min_api_version = minApiVersion;
Fix Formatting issue

2019-03-14 11:06 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastUrlMessage.xml
> +            payload.tracking_data = trackingData;
Fix Formatting issue

2019-03-14 11:06 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastUrlMessage.xml
> +            if( trackingData != null && trackingData != ""){
```suggestion
            if(trackingData != null && trackingData != "") {
```

2019-03-14 11:06 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastVideoMessage.xml
> +            payload.sender.avatar = senderAvatarUrl;
Fix Formatting issue

2019-03-14 11:07 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastVideoMessage.xml
> +            if ( senderAvatarUrl != null && senderAvatarUrl != "") {
```suggestion
            if (senderAvatarUrl != null && senderAvatarUrl != "") {
```

2019-03-14 11:07 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastVideoMessage.xml
> +            if( trackingData != null && trackingData != ""){
```suggestion
            if(trackingData != null && trackingData != "") {
```

2019-03-14 11:07 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastVideoMessage.xml
> +            payload.tracking_data = trackingData;
Fix Formatting issue

2019-03-14 11:07 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastVideoMessage.xml
> +            if( minApiVersion != null && minApiVersion != ""){
```suggestion
            if(minApiVersion != null && minApiVersion != "") {
```

2019-03-14 11:08 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastVideoMessage.xml
> +            payload.min_api_version = minApiVersion;
Fix Formatting issue

2019-03-14 11:08 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastVideoMessage.xml
> +            payload.thumbnail = thumbnailUrl;
Fix Formatting issue

2019-03-14 11:08 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastVideoMessage.xml
> +            if( thumbnailUrl != null && thumbnailUrl != ""){
```suggestion
            if(thumbnailUrl != null && thumbnailUrl != "") {
```

2019-03-14 11:08 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastVideoMessage.xml
> +            payload.duration = duration;
Fix Formatting issue

2019-03-14 11:08 UTC, Biruntha commented on src/main/resources/broadcastMessage/broadcastVideoMessage.xml
> +            if( duration != null && duration != ""){
```suggestion
            if(duration != null && duration != "") {
```

2019-03-14 11:09 UTC, Biruntha commented on src/main/resources/keyboardMessage/sendKeyboardCarouselContent.xml
> +            mc.setPayloadJSON(payload);
Fix all Formatting issues inside the script mediator

2019-03-14 11:09 UTC, Biruntha commented on src/main/resources/keyboardMessage/sendKeyboardContact.xml
> +            mc.setPayloadJSON(payload);
Fix all Formatting issues inside the script mediator

2019-03-14 11:10 UTC, Biruntha commented on src/main/resources/keyboardMessage/sendKeyboardFile.xml
> +
Fix all Formatting issues inside the script mediator

2019-03-14 11:10 UTC, Biruntha commented on src/main/resources/keyboardMessage/sendKeyboardLocation.xml
> +            mc.setPayloadJSON(payload);
Fix all Formatting issues inside the script mediator

2019-03-14 11:10 UTC, Biruntha commented on src/main/resources/keyboardMessage/sendKeyboardPicture.xml
> +
Fix all Formatting issues inside the script mediator

2019-03-14 11:10 UTC, Biruntha commented on src/main/resources/keyboardMessage/sendKeyboardSticker.xml
> +
Fix all Formatting issues inside the script mediator

2019-03-14 11:11 UTC, Biruntha commented on src/main/resources/keyboardMessage/sendKeyboardText.xml
> +            mc.setPayloadJSON(payload);
Fix all Formatting issues inside the script mediator

2019-03-14 11:11 UTC, Biruntha commented on src/main/resources/keyboardMessage/sendKeyboardUrl.xml
> +            mc.setPayloadJSON(payload);
Fix all Formatting issues inside the script mediator

2019-03-14 11:11 UTC, Biruntha commented on src/main/resources/message/sendCarouselContentMessage.xml
> +
Fix all Formatting issues inside the script mediator

2019-03-14 11:11 UTC, Biruntha commented on src/main/resources/message/sendContactMessage.xml
> +            mc.setPayloadJSON(payload);
Fix all Formatting issues inside the script mediator

2019-03-14 11:11 UTC, Biruntha commented on src/main/resources/message/sendFileMessage.xml
> +
Fix all Formatting issues inside the script mediator

2019-03-14 11:12 UTC, Biruntha commented on src/main/resources/message/sendLocationMessage.xml
> +            mc.setPayloadJSON(payload);
Fix all Formatting issues inside the script mediator

2019-03-14 11:12 UTC, Biruntha commented on src/main/resources/message/sendPictureMessage.xml
> +            mc.setPayloadJSON(payload);
Fix all Formatting issues inside the script mediator

2019-03-14 11:12 UTC, Biruntha commented on src/main/resources/message/sendStickerMessage.xml
> +            mc.setPayloadJSON(payload);
Fix all Formatting issues inside the script mediator

2019-03-14 11:13 UTC, Biruntha commented on src/main/resources/message/sendTextMessage.xml
> +            mc.setPayloadJSON(payload);
Fix all Formatting issues inside the script mediator

2019-03-14 11:13 UTC, Biruntha commented on src/main/resources/message/sendUrlMessage.xml
> +
Fix all Formatting issues inside the script mediator
Can you check other file and fix

2019-03-14 11:13 UTC, Biruntha commented on src/test/INTEGRATION_TEST.md
> +##Integration tests for WSO2 ESB Viber connector
```suggestion
##Integration tests for WSO2 EI Viber connector
```

2019-03-14 11:15 UTC, Biruntha commented on src/test/java/org/wso2/carbon/connector/integration/test/viber/ViberConnectorIntegrationTest.java
> +                apiRestResponse.getBody().getJSONArray("members").getJSONObject(1).
You can move this line to above. Check in other places

2019-03-14 11:15 UTC, Biruntha commented on src/test/java/org/wso2/carbon/connector/integration/test/viber/ViberConnectorIntegrationTest.java
> +
Remove extra line

2019-03-14 11:16 UTC, Biruntha commented on src/test/java/org/wso2/carbon/connector/integration/test/viber/ViberConnectorIntegrationTest.java
> +
Remove extra line

2019-03-14 11:18 UTC, Biruntha commented on src/test/java/org/wso2/carbon/connector/integration/test/viber/ViberConnectorIntegrationTest.java
> +        ;
Why  ; 

Remove this char

2019-03-18 08:31 UTC, Kanapriya approved these changes

2019-03-18 09:11 UTC, Kanapriya approved these changes

2019-03-18 09:11 UTC, merged